<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <UseAppHost>false</UseAppHost>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <HelEngineRoot Condition="'$(HelEngineRoot)' == ''">..\..\helengine</HelEngineRoot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Shaderc" Version="2.21.0" />
    <PackageReference Include="Silk.NET.Shaderc.Native" Version="2.21.0" />
    <PackageReference Include="Silk.NET.SPIRV.Cross" Version="2.21.0" />
    <PackageReference Include="Silk.NET.SPIRV.Cross.Native" Version="2.21.0" />
    <ProjectReference Include="$(HelEngineRoot)\engine\helengine.baseplatform\helengine.baseplatform.csproj" />
    <ProjectReference Include="$(HelEngineRoot)\engine\helengine.core\helengine.core.csproj" />
    <ProjectReference Include="$(HelEngineRoot)\engine\helengine.files\helengine.files.csproj" />
    <ProjectReference Include="$(HelEngineRoot)\engine\helengine.shader.compilation\helengine.shader.compilation.csproj" />
  </ItemGroup>
</Project>
